version: '3'

services:
  app:
    build: app/
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    restart: always
    volumes:
      - ./app/static:/usr/src/app/static
    ports:
      - "8080:8080"

    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    logging:
      options:
        max-size: "200M"
        max-file: "4"
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
