# Generated by Django 4.0 on 2021-12-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
